//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAGestPerso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tach
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string description { get; set; }
        public string fichiers { get; set; }
        public short importance { get; set; }
        public System.DateTime date_saisie { get; set; }
        public Nullable<int> utilisateur { get; set; }
    
        public virtual Tach Taches1 { get; set; }
        public virtual Tach Tach1 { get; set; }
        public virtual Utilisateur Utilisateur1 { get; set; }
    }
}
